### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by GyspyBoy123** [1132719438/pynvx#1]
Running this install on MacOS [https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#anaconda](url)

but get this error when I try to run the `python faceswap.py -h` or `python faceswap.py gui`

`Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "/Users/dwalshjones/faceswap/lib/cli.py", line 11, in <module>
    from lib.logger import crash_log, log_setup
  File "/Users/dwalshjones/faceswap/lib/logger.py", line 15, in <module>
    from lib.sysinfo import sysinfo
  File "/Users/dwalshjones/faceswap/lib/sysinfo.py", line 11, in <module>
    from lib.gpu_stats import GPUStats
  File "/Users/dwalshjones/faceswap/lib/gpu_stats.py", line 8, in <module>
    import pynvx  # pylint: disable=import-error
ImportError: No module named 'pynvx'`

**Comment by 1132719438** [comment]
Try to manually install pynvx
`
pip install pynvx
`

**Comment by GyspyBoy123** [comment]
I've tried that too, it just comes up with

`Collecting pynvx
  Using cached https://files.pythonhosted.org/packages/02/c6/90f26fee13f4b264946f74ece86b815cb01cc07035c2c5c80ab82f690a4f/pynvx-0.0.4.tar.gz
Building wheels for collected packages: pynvx
  Running setup.py bdist_wheel for pynvx ... error
  Complete output from command /anaconda3/envs/faceswap/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-wheel-eh34m3aj --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is AppleClang 10.0.0.10001044
  -- The CXX compiler identification is AppleClang 10.0.0.10001044
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /anaconda3/envs/faceswap/bin/python (found version "3.5.5")
  -- Found PythonLibs: /anaconda3/envs/faceswap/lib/libpython3.5m.dylib
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.3.dev0
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  CMake Error at /anaconda3/envs/faceswap/lib/python3.5/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.12/Modules/FindCUDA.cmake:692 (message):
    Specify CUDA_TOOLKIT_ROOT_DIR
  Call Stack (most recent call first):
    CMakeLists.txt:8 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/build/temp.macosx-10.9-x86_64-3.5/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 107, in <module>
      "Topic :: Software Development :: Libraries :: Python Modules",
    File "/anaconda3/envs/faceswap/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/anaconda3/envs/faceswap/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 32, in run
      self.build_extension(ext)
    File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/anaconda3/envs/faceswap/lib/python3.5/subprocess.py", line 271, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/build/lib.macosx-10.9-x86_64-3.5', '-DPYTHON_EXECUTABLE=/anaconda3/envs/faceswap/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pynvx
  Running setup.py clean for pynvx
Failed to build pynvx
Installing collected packages: pynvx
  Running setup.py install for pynvx ... error
    Complete output from command /anaconda3/envs/faceswap/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-record-bv0yx1_i/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    -- The C compiler identification is AppleClang 10.0.0.10001044
    -- The CXX compiler identification is AppleClang 10.0.0.10001044
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /anaconda3/envs/faceswap/bin/python (found version "3.5.5")
    -- Found PythonLibs: /anaconda3/envs/faceswap/lib/libpython3.5m.dylib
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.3.dev0
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    CMake Error at /anaconda3/envs/faceswap/lib/python3.5/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.12/Modules/FindCUDA.cmake:692 (message):
      Specify CUDA_TOOLKIT_ROOT_DIR
    Call Stack (most recent call first):
      CMakeLists.txt:8 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/build/temp.macosx-10.9-x86_64-3.5/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 107, in <module>
        "Topic :: Software Development :: Libraries :: Python Modules",
      File "/anaconda3/envs/faceswap/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/faceswap/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/envs/faceswap/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 32, in run
        self.build_extension(ext)
      File "/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/anaconda3/envs/faceswap/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/build/lib.macosx-10.9-x86_64-3.5', '-DPYTHON_EXECUTABLE=/anaconda3/envs/faceswap/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/anaconda3/envs/faceswap/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-record-bv0yx1_i/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/z6/8l5wrhp13vbg8h5sjqnfxspw0000gn/T/pip-install-vzwdx8sg/pynvx/`

**Comment by 1132719438** [comment]
Try https://github.com/1132719438/pynvx/blob/master/TROUBLESHOOTING.md

**Comment by 1132719438** [comment]
Hi @GyspyBoy123, I will close this issue because no respond, feel free to reopen it if you need help.
